Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Metrics/LineLength:
  Max: 90

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'